apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: example
spec:
  description: Example Tekton pipeline
  tasks:
    - name: hello
      taskRef:
        name: echo
      params:
        - name: message
          value: "Hello from Planton"
